import { MetricCard } from "@/components/ui/metric-card";
import { formatCompactNumber } from "@/lib/formatters";
import type { ChannelAnalysis } from "@/types/youtube";

type SummaryCardsProps = {
  analysis: ChannelAnalysis;
  onPresetSelect: (preset: "winners" | "views" | "fresh" | "velocity" | "breakout") => void;
  activePreset: "winners" | "views" | "fresh" | "velocity" | "breakout" | null;
};

export function SummaryCards({
  analysis,
  onPresetSelect,
  activePreset,
}: SummaryCardsProps) {
  const { metrics } = analysis;

  return (
    <div className="fade-up grid gap-4 sm:grid-cols-2 xl:grid-cols-5">
      <MetricCard
        label="Winners this month"
        value={`${metrics.monthlyWinners}`}
        detail={`${metrics.monthlyWinners} uploads are currently outperforming the channel baseline.`}
        emphasis
        actionLabel="Open winners"
        active={activePreset === "winners"}
        onClick={() => onPresetSelect("winners")}
      />
      <MetricCard
        label="Monthly views"
        value={formatCompactNumber(metrics.totalRecentViews)}
        detail="Views generated by uploads published inside the current 30-day window."
        actionLabel="Sort by reach"
        active={activePreset === "views"}
        onClick={() => onPresetSelect("views")}
      />
      <MetricCard
        label="Uploads this month"
        value={`${metrics.videosThisMonth}`}
        detail="Videos published inside the current 30-day scan window."
        actionLabel="Focus recent"
        active={activePreset === "fresh"}
        onClick={() => onPresetSelect("fresh")}
      />
      <MetricCard
        label="Avg views / day"
        value={formatCompactNumber(metrics.averageViewsPerDay)}
        detail="Average daily velocity across the current scan."
        actionLabel="Sort by velocity"
        active={activePreset === "velocity"}
        onClick={() => onPresetSelect("velocity")}
      />
      <MetricCard
        label="Breakout count"
        value={`${metrics.breakoutCount}`}
        detail="Uploads in the current window that are still accelerating above baseline."
        actionLabel="Open breakouts"
        active={activePreset === "breakout"}
        onClick={() => onPresetSelect("breakout")}
      />
    </div>
  );
}
